import { NextResponse } from 'next/server'
import { getCurrentAccount } from '@/lib/auth/account'

/**
 * GET /api/ai/assessments
 *
 * Returns a list of customer assessments generated by the AI sales agent.
 * Accessible by any account member. Supports filtering by interest level.
 */
export async function GET(request: Request) {
  try {
    const { supabase, accountId } = await getCurrentAccount()
    const { searchParams } = new URL(request.url)

    const interestLevel = searchParams.get('interest_level')
    const limit = Math.min(100, Math.max(1, Number(searchParams.get('limit') || 50)))

    let query = supabase
      .from('ai_customer_assessments')
      .select(`
        id,
        conversation_id,
        contact_id,
        interest_level,
        collected_data,
        ai_reasoning,
        actions_taken,
        created_at,
        contacts (
          name,
          phone
        )
      `)
      .eq('account_id', accountId)
      .order('created_at', { ascending: false })
      .limit(limit)

    if (interestLevel && interestLevel !== 'all') {
      query = query.eq('interest_level', interestLevel)
    }

    const { data, error } = await query

    if (error) {
      console.error('[ai/assessments GET] query error:', error)
      return NextResponse.json(
        { error: 'Failed to fetch AI assessments' },
        { status: 500 },
      )
    }

    // Map nested contact data for flat consumption on frontend
    const formatted = (data || []).map((row: any) => ({
      id: row.id,
      conversationId: row.conversation_id,
      contactId: row.contact_id,
      interestLevel: row.interest_level,
      collectedData: row.collected_data,
      aiReasoning: row.ai_reasoning,
      actionsTaken: row.actions_taken || [],
      createdAt: row.created_at,
      contactName: row.contacts?.name || 'Unknown Contact',
      contactPhone: row.contacts?.phone || '',
    }))

    return NextResponse.json({ assessments: formatted })
  } catch (err) {
    console.error('[ai/assessments GET] error:', err)
    return NextResponse.json(
      { error: 'Internal Server Error' },
      { status: 500 },
    )
  }
}
